#live processing with guppy R10

source("c:/Users/sturgeon/Desktop/sturgeon/R_scripts/peroperative_seq_functions_windows.R")

#make sure the probes file corresponds to the refgenome used by minknow, and that linux format path is used
probes_file = "/mnt/c/Users/sturgeon/Desktop/sturgeon/R_scripts/probelocs_chm13.bed"
model_file = "/mnt/c/Users/sturgeon/Desktop/sturgeon_files/model.zip"


print("loaded")

#FILL!! in the POD5 output folder as generated by minKnow.
#autofil (tab) works once run has started with the pore scan
pod5_folder="c:/Users/sturgeon/Desktop/sturgeon_files/basecalling_test/" #to change, ends with "/pod5/"
#FILL BARCODE
bcoverride = 23
#USE unclassified barcodes yes (T) or no (F)
use_unclassified = T

#FILL!! main folder for data output, will be generated
main_folder = "c:/Users/sturgeon/Desktop/sturgeon_files/result_test/"


#DO NOT TOUCH ANYTHING BELOW THIS LINE ----

main_folder_wsl = gsub(pattern=":", replacement="", x=main_folder)
main_folder_wsl = paste0("/mnt/", main_folder_wsl)

if(exists("iteration")==F){
  iteration = 1}

CNV_iterations = c(10,15, 20, 25,30)

#make the main_folder using windows shell
if(file.exists(main_folder)==F){
  dir.create(main_folder)}
setwd(main_folder)
#functioncheck_guppy()

#don't change any of these
running = T
progress = data.frame()

if(nchar(bcoverride)==1){
  bcoverride = paste0("0",bcoverride)
}

progress = data.frame()
while(running == T){
  #make an iteration directory
  dir.create(paste0(main_folder,"/iteration",iteration))
  
  #if(iteration==6){running=F}
  if(file.exists("processed_files.txt")){
    processed_files = read.table("processed_files.txt", header=T)}else{
      processed_files=data.frame()
      }
  #keep track of processed files
  #check if there are new files, if not, wait 30 seconds and check again
  pass_bams = list.files(paste0(pod5_folder,"/pass/barcode",bcoverride,"/"), pattern = "bam_runid", full.names = T)
  if(use_unclassified==T){
    unclassified_bams = list.files(paste0(pod5_folder,"/pass/unclassified/"), pattern = "bam_runid", full.names = T)
    pass_bams = c(pass_bams, unclassified_bams)
  }
  
  pass_bams=pass_bams[!pass_bams %in% processed_files$bams]
  
  if(length(pass_bams)==0){
    print("no new bam files, waiting 15 seconds")
    Sys.sleep(15)
  }else{
    print("new file(s) found, running pipeline")
    #fail_bams = list.files(paste0(pod5_folder,"/fail/barcode",bcoverride,"/"), pattern = "bam_runid", full.names = T)
    
    #change pass_bams to wsl directories
    pass_bams_wsl = gsub(pattern=":", replacement="", x=pass_bams)
    #add /mnt/ to every entry in pass_bams_wsl
    pass_bams_wsl = paste0("/mnt/", pass_bams_wsl)
    
    #merge the .bam files using wsl
    tomerge = paste0(pass_bams_wsl, collapse=" ")
    command=paste0("wsl ", samtools_location," merge -@ 10 -o iteration",iteration,"/merged.bam ", tomerge)
    shell(command)
    
    #sort the merged bam file
    command=paste0("wsl ", samtools_location," sort -@ 10 -o merged_srt_",iteration,".bam iteration",iteration,"/merged.bam")
    shell(command)
    
    #run_sturgeon
    stgncommand = paste("wsl",sturgeon_shell, main_folder_wsl, probes_file, model_file)
    shell(stgncommand)
   
    #add iteration results to the progress dataframe, and make a plot
    progress = try(add_and_plot_windows(progress, paste0(main_folder, "/merged_probes_methyl_calls_model.csv")), silent=T)
    try(write.table(progress, file=paste0(main_folder,"/classifier_progress.txt"), quote=F, row.names = F), silent=T)
    pdf(file=paste0(main_folder,"confidence_over_time_plot.pdf"))
    try(confidence_over_time_plot_windows(merged_data = progress), silent=T)
    dev.off()
    
    Sys.sleep(1)
    if(iteration%in%CNV_iterations){
      if(dir.exists("CNV_data")==F){dir.create("CNV_data")}
      itbams = list.files(pattern="merged_srt_", full.names = T)
      itbams=itbams[grepl(".bam", itbams)]
      itbams=itbams[grepl(".bai", itbams)==F]
      itbams = paste0(itbams, collapse=" ")
      samtools_comm = paste0("wsl ", samtools_location," merge -@ 10 -o CNV_data/data_cnv_it_",iteration,".bam ", itbams)
      shell(samtools_comm)
      
      pdf(file=paste0(main_folder,"/CNV_plot_iteration",iteration,".pdf"),useDingbats = F)
      try(plot_cnv_from_bam_DNAcopy(paste0(main_folder,"CNV_data/data_cnv_it_",iteration,".bam")), silent=T)
      dev.off()
      
      try(shell(paste0("open ", main_folder,"/CNV_plot_iteration",iteration,".pdf")), silent=T)
      Sys.sleep(1)}
    
    #update iteration nr
    iteration=iteration+1
    #update list of processed bam files
    processed_files = rbind(processed_files, data.frame(iteration=iteration, bams=pass_bams))
    write.table(processed_files, file="processed_files.txt", quote=F, row.names = F)
    
  }}


