#reproduce outcomes and figures of a sturgeon run
#this script takes outputs of a live run and reruns the classification part using Sturgeon.
#it does not rerun basecalling, mapping and methylation calling, but uses megalodon output files instead

#the input directory, as generated by "live_processing_fast5s_v2.0.R
#should contain subdirectories "iteration_x" 
indir="~/nanocns/data/live_run_4/"
#the output directory
outdir = "~/nanocns/data/reproduce_live_4_v2_model/"
system(paste0("mkdir ", outdir))
system(paste0("rm ", outdir,"*"))
#limit to the number of iterations to  be re-run
iterations = 10
#barcode used for this sample
barcode = 4
#1:1
#2:2
#3:3
#4:4

library(rhdf5)
#source a file with functions
source("~/nanocns/R-scripts/peroperative_sequencing_functions.R")

#make an empty frame to show performance over time
progress = data.frame()
#figure out the read names
readnames= read.table(paste0(indir, "/iteration_1/barcoding.tsv"),header=T)
readnames=readnames[readnames$barcode==barcode,]
#trim iterations from the start if the intended barcode is not found (happens if a chip is reused and the library is loaded a while after starting the run)
startit=1
while(nrow(readnames)<10){
  startit=startit+1
  readnames= read.table(paste0(indir, "/iteration_",startit,"/barcoding.tsv"),header=T)
  readnames=readnames[readnames$barcode==barcode,]
  }

#read a sequencing summary to figure out how long each iteration took.
#4
summary=read.table("/var/lib/minknow/data/live_run_4/no_sample/20221215_1135_MN40352_FAT51400_9cc494d1/sequencing_summary_FAT51400_9cc494d1_1fedb22a.txt", header=T)
#3:summary=read.table("/var/lib/minknow/data/live_run_3/no_sample/20221213_1248_MN40352_FAV00525_44b348ce/sequencing_summary_FAV00525_44b348ce_cf15214f.txt", header=T)
#2:summary=read.table("/var/lib/minknow/data/live_run_2/no_sample/20221208_1419_MN40352_FAV00525_adfaaf3f/sequencing_summary_FAV00525_adfaaf3f_1e8ad907.txt", header=T)
#1:
#summary=read.table("/var/lib/minknow/data/live-run_1/no_sample/20221206_1241_MN40352_FAV45219_17d67c33/sequencing_summary_FAV45219_17d67c33_bacd524a.txt", header=T)
summary$endtime=summary$start_time+summary$duration
starttime=min(summary[summary$read_id%in%readnames$name,"start_time"])

metrics = data.frame(it=1:10, duration="x", probesites="x", tophit="x",maxscore="x")
itcounter = 1
#iteratively process each fast5 batch
for(it in startit:(startit+iterations)){
  system(paste0("cp ",indir, "/per_read_modified_base_calls_it",it, ".txt ", outdir))
  #system(paste0("mkdir ", outdir,"results/"))
  #system(paste0("rm ", outdir,"results/*"))
  
  #run sturgeon through a shell script
  system(paste0("~/Carlo/run_sturgeon_tobed_v2.sh ", outdir," ",outdir))
  
  #figure out when the last read was finished
  readnames= read.table(paste0(indir,"/iteration_",it,"/barcoding.tsv"),header=T)
  seqtime = (max(summary[summary$read_id%in%readnames$name,"endtime"])-starttime)/60
  metrics[metrics$it==itcounter,"duration"]=seqtime
  
  #process the sturgeon results
  reslist_2 = t(data.frame(read.table(paste0(outdir,"merged_probes_methyl_calls_model.csv"), sep=",")))
  metrics[metrics$it==itcounter,"probesites"]=as.numeric(reslist_2[1,2])
  reslist_2=reslist_2[2:nrow(reslist_2),]
  colnames(reslist_2)=c("class", "score")
  reslist_2=data.frame(reslist_2)
  reslist_2$score=as.numeric(reslist_2$score)
  tophit = reslist_2[reslist_2$score==max(reslist_2$score),]
  
  metrics[metrics$it==itcounter,"tophit"]=tophit$class
  metrics[metrics$it==itcounter,"maxscore"]=tophit$score
  print(paste0("iteration ", it, " duration: ", seqtime, " minutes"))
  
  #update the result datafframe and plot
  progress = add_and_plot(progress,paste0(outdir,"merged_probes_methyl_calls_model.csv" ))
  pdf(file=paste0(outdir,"performance_over_time.pdf"))
  bla=add_and_plot(progress,paste0(outdir,"merged_probes_methyl_calls_model.csv" ))
  dev.off()
  itcounter=itcounter+1
}

write.table(metrics, file=paste0(outdir,"/metrics_live_1.txt"), sep=",", quote=F, row.names=F)
metrics
